### ISSUE TITLE
vue封装axios | WestLonely

### ISSUE THREAD

**Issue by wjqh** [wjqh/wjqh.github.io#4]
https://biubu.cn/2018/07/06/vue%E5%B0%81%E8%A3%85axios/

**Comment by jinxuejie** [comment]
我整了半天GitHub就是为了评论一下你，你看看你最后的结果，是不是要这样调用 
API.getData('list',{data:'listData'})
      .then(result => {
            console.log(result);
      },reason => {
            console.log(reason);
      })，，
我就想说，你这样整一大堆没有用的，纯粹瞎折腾，看看没有封装之前是怎么用的，你就会恍然大悟，误导读者：
 axios.post(url,params).then(result => {
           console.log(result);//成功回调
        },reason => {
             console.log(reason)//失败回调
        })

看出来了吗，区别在哪？有没有简化代码？何必瞎折腾呢？

**Comment by wjqh** [comment]
> 我整了半天GitHub就是为了评论一下你，你看看你最后的结果，是不是要这样调用
> API.getData('list',{data:'listData'})
> .then(result => {
> console.log(result);
> },reason => {
> console.log(reason);
> })，，
> 我就想说，你这样整一大堆没有用的，纯粹瞎折腾，看看没有封装之前是怎么用的，你就会恍然大悟，误导读者：
> axios.post(url,params).then(result => {
> console.log(result);//成功回调
> },reason => {
> console.log(reason)//失败回调
> })
> 
> 看出来了吗，区别在哪？有没有简化代码？何必瞎折腾呢？



> 我整了半天GitHub就是为了评论一下你，你看看你最后的结果，是不是要这样调用
> API.getData('list',{data:'listData'})
> .then(result => {
> console.log(result);
> },reason => {
> console.log(reason);
> })，，
> 我就想说，你这样整一大堆没有用的，纯粹瞎折腾，看看没有封装之前是怎么用的，你就会恍然大悟，误导读者：
> axios.post(url,params).then(result => {
> console.log(result);//成功回调
> },reason => {
> console.log(reason)//失败回调
> })
> 
> 看出来了吗，区别在哪？有没有简化代码？何必瞎折腾呢？

首先，感谢，你说的的确有道理。
我们项目是这么用的，还有以下考虑：
1 对post 请求发送的json数据要同意装换成字符串
2 要对借口返回的数据统一进行验证是不是符合规范的，符合规范的，直接使用，不符合规范的，抛出错误，所以对 API 进行了封装。

以上两点文章里面没有体现。

我之前也写过你用的第二种方式，但后来发现，后端给的接口地址后面的都是定的，前面的ＩＰ部分才会改变，开发环境和生产环境要切换的只是ＩＰ的部分。所以就把变化的部分提出来了。

**Comment by wjqh** [comment]
> > 我整了半天GitHub就是为了评论一下你，你看看你最后的结果，是不是要这样调用
> > API.getData('list',{data:'listData'})
> > .then(result => {
> > console.log(result);
> > },reason => {
> > console.log(reason);
> > })，，
> > 我就想说，你这样整一大堆没有用的，纯粹瞎折腾，看看没有封装之前是怎么用的，你就会恍然大悟，误导读者：
> > axios.post(url,params).then(result => {
> > console.log(result);//成功回调
> > },reason => {
> > console.log(reason)//失败回调
> > })
> > 看出来了吗，区别在哪？有没有简化代码？何必瞎折腾呢？
> 
> 首先，感谢，你说的的确有道理。
> 我们项目是这么用的，还有以下考虑：
> 1 对post 请求发送的json数据要同意装换成字符串
> 2 要对借口返回的数据统一进行验证是不是符合规范的，符合规范的，直接使用，不符合规范的，抛出错误，所以对 API 进行了封装。
> 
> 以上两点文章里面没有体现。
> 
> 我之前也写过你用的第二种方式，但后来发现，后端给的接口地址后面的都是定的，前面的ＩＰ部分才会改变，开发环境和生产环境要切换的只是ＩＰ的部分。所以就把变化的部分提出来了。
